from typing import Any

class SentimentIntensityAnalyzer:
    def __init__(self, lexicon_file: str = ..., emoji_lexicon: str = ...) -> None: ...
    def polarity_scores(self, text: str) -> dict[str, float]: ...
